"""
StateManager — manages state.json lifecycle.

state.json stores the bot's E2EE private keys and identity information.
It is generated by `xchat unlock` and must never be committed to git.

File format::

    {
        "private_keys": {
            "1": "<base64-encoded X25519 private key>",
            "2": "<base64-encoded X25519 private key>"
        },
        "signing_key_version": "2",
        "user_id": "123456789"
    }
"""

from __future__ import annotations

import json
import os
from pathlib import Path


class StateManager:
    """Manages reading and writing state.json.

    Args:
        state_file: Path to state.json. Defaults to ./state.json.

    Usage::

        manager = StateManager()
        key = manager.get_latest_key()   # base64 private key
        user_id = manager.user_id
    """

    def __init__(self, state_file: Path = Path("state.json")) -> None:
        self._state_file = state_file
        self._state: dict[str, object] = {}

    def load(self) -> None:
        """Load state.json from disk.

        Raises:
            FileNotFoundError: If state.json does not exist.
            ValueError: If state.json is malformed.
        """
        if not self._state_file.exists():
            raise FileNotFoundError(
                f"state.json not found at {self._state_file}. "
                "Run `xchat unlock` to generate it."
            )
        try:
            self._state = json.loads(self._state_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"state.json is not valid JSON: {exc}") from exc

    def save(self) -> None:
        """Write current state to disk with restricted permissions (600)."""
        self._state_file.write_text(
            json.dumps(self._state, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        # Restrict to owner read/write only
        os.chmod(self._state_file, 0o600)

    def is_loaded(self) -> bool:
        """Return True if state has been loaded from disk."""
        return bool(self._state)

    # ── Key access ────────────────────────────────────────────────────────

    @property
    def private_keys(self) -> dict[str, str]:
        """All private keys, keyed by version string."""
        return self._state.get("private_keys", {})  # type: ignore[return-value]

    def get_private_key(self, version: str) -> str | None:
        """Return the base64-encoded private key for a given version."""
        return self.private_keys.get(version)

    def get_latest_key(self) -> tuple[str, str] | None:
        """Return (version, base64_key) for the highest-numbered key version.

        Returns None if no keys are available.
        """
        keys = self.private_keys
        if not keys:
            return None
        try:
            latest_version = str(max(int(k) for k in keys.keys()))
        except (ValueError, TypeError):
            latest_version = list(keys.keys())[-1]
        return latest_version, keys[latest_version]

    def set_private_key(self, version: str, key_b64: str) -> None:
        """Store a private key (used by `xchat unlock`)."""
        if "private_keys" not in self._state:
            self._state["private_keys"] = {}
        self._state["private_keys"][version] = key_b64  # type: ignore[index]

    # ── Identity ──────────────────────────────────────────────────────────

    @property
    def user_id(self) -> str | None:
        """Bot's X user ID."""
        return self._state.get("user_id")  # type: ignore[return-value]

    @user_id.setter
    def user_id(self, value: str) -> None:
        self._state["user_id"] = value

    @property
    def signing_key_version(self) -> str | None:
        """Current signing key version."""
        return self._state.get("signing_key_version")  # type: ignore[return-value]

    @signing_key_version.setter
    def signing_key_version(self, value: str) -> None:
        self._state["signing_key_version"] = value

    # ── Validation ────────────────────────────────────────────────────────

    def validate(self) -> list[str]:
        """Return a list of validation errors (empty = valid)."""
        errors: list[str] = []
        if not self.private_keys:
            errors.append("private_keys is empty — run `xchat unlock`")
        if not self.user_id:
            errors.append("user_id is missing — run `xchat unlock`")
        return errors
