"""
RealCrypto — production E2EE decryption adapter.

EXPERIMENTAL STATUS:
  chat-xdk has not been officially released as a stable public library.
  This implementation follows the observed pattern from xchat-bot-python
  but the actual decryption call is a placeholder pending chat-xdk stabilization.

  When chat-xdk is officially released:
  1. Replace the _xchacha20_decrypt() placeholder with the real implementation
  2. Remove the EXPERIMENTAL warning from this docstring
  3. Update the notes field in DecryptResult

  Until then, this adapter will:
  - Load state.json and validate its structure
  - Return a clear DecryptResult with notes explaining the placeholder status
  - Fall back to StubCrypto for STUB_ENC_ payloads (useful in mixed environments)

Requires:
  - state.json with private_keys (generated by `xchat unlock`)
  - cryptography >= 42.0 (for future XChaCha20-Poly1305 support)
"""

from __future__ import annotations

import json
from pathlib import Path

from xchat_bot.crypto.stub import STUB_PREFIX, StubCrypto
from xchat_bot.events.models import DecryptResult


class RealCrypto:
    """Real E2EE decryption adapter using state.json private keys.

    EXPERIMENTAL: The actual decryption is a placeholder until chat-xdk is stable.

    Args:
        state_file: Path to state.json (generated by `xchat unlock`).

    Raises:
        FileNotFoundError: If state_file does not exist.
        ValueError: If state_file is malformed (missing private_keys).
    """

    def __init__(self, state_file: Path = Path("state.json")) -> None:
        self._state_file = state_file
        self._state: dict[str, object] = {}
        self._load_state()

    def _load_state(self) -> None:
        if not self._state_file.exists():
            raise FileNotFoundError(
                f"state.json not found at {self._state_file}. "
                "Run `xchat unlock` to generate it. "
                "This file contains your E2EE private keys — never commit it to git."
            )
        try:
            self._state = json.loads(self._state_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(
                f"state.json at {self._state_file} is not valid JSON: {exc}"
            ) from exc

        if "private_keys" not in self._state:
            raise ValueError(
                f"state.json at {self._state_file} is missing 'private_keys'. "
                "Re-run `xchat unlock` to regenerate it."
            )

    def decrypt(
        self,
        encoded_event: str,
        encrypted_conversation_key: str | None = None,
    ) -> DecryptResult:
        """Attempt to decrypt a real XChat message payload.

        EXPERIMENTAL: The actual XChaCha20-Poly1305 decryption is a placeholder
        pending chat-xdk official release. This method validates the key material
        is present and returns a clear status.

        Args:
            encoded_event: The encoded_event field from data.payload.
            encrypted_conversation_key: The encrypted_conversation_key from data.payload.

        Returns:
            DecryptResult. plaintext is None until chat-xdk placeholder is resolved.
        """
        # Fall back to stub for STUB_ENC_ payloads (useful in mixed test/prod environments)
        if encoded_event.startswith(STUB_PREFIX):
            stub_result = StubCrypto().decrypt(encoded_event, encrypted_conversation_key)
            return DecryptResult(
                plaintext=stub_result.plaintext,
                mode="real-fallback-stub",
                key_id=self._get_latest_key_version(),
                notes="Stub payload detected in real mode — decoded via StubCrypto fallback",
            )

        private_keys: dict[str, str] = self._state.get("private_keys", {})  # type: ignore[assignment]
        if not private_keys:
            return DecryptResult(
                plaintext=None,
                mode="real",
                key_id=None,
                notes=(
                    "No private_keys found in state.json. "
                    "Re-run `xchat unlock` to populate them."
                ),
            )

        key_version = self._get_latest_key_version()

        # PLACEHOLDER: Real XChaCha20-Poly1305 decryption
        # This will be implemented when chat-xdk is officially released.
        # Expected flow:
        #   1. base64-decode encoded_event
        #   2. base64-decode encrypted_conversation_key
        #   3. Use private_keys[key_version] (X25519 private key) to derive shared secret
        #   4. Use shared secret to decrypt conversation key (ECDH + KDF)
        #   5. Use conversation key to decrypt encoded_event (XChaCha20-Poly1305)
        return DecryptResult(
            plaintext=None,
            mode="real",
            key_id=key_version,
            notes=(
                "EXPERIMENTAL: Real decryption is a placeholder. "
                "chat-xdk has not been officially released as a stable library. "
                "This will be implemented when the official API is published. "
                f"Key version available: {key_version}. "
                "Track progress at: https://github.com/twitterdev/xchat-bot-python"
            ),
        )

    def encrypt(self, plaintext: str) -> str:
        """Not implemented for real crypto — use StubCrypto for test fixtures."""
        raise NotImplementedError(
            "RealCrypto.encrypt() is not implemented. "
            "Use StubCrypto for generating test fixtures."
        )

    def get_latest_key(self) -> tuple[str, str] | None:
        """Return (version, base64_key) for the highest-numbered key version.

        Returns None if no keys are available.
        """
        private_keys: dict[str, str] = self._state.get("private_keys", {})  # type: ignore[assignment]
        if not private_keys:
            return None
        version = self._get_latest_key_version()
        if version is None:
            return None
        return version, private_keys[version]

    def _get_latest_key_version(self) -> str | None:
        """Return the highest available private key version."""
        private_keys: dict[str, str] = self._state.get("private_keys", {})  # type: ignore[assignment]
        if not private_keys:
            return None
        try:
            return str(max(int(k) for k in private_keys.keys()))
        except (ValueError, TypeError):
            # Non-integer keys — return last key
            return list(private_keys.keys())[-1]

    def get_private_key(self, version: str) -> str | None:
        """Return the base64-encoded private key for a given version.

        Args:
            version: Key version string (e.g. "1", "2").

        Returns:
            Base64-encoded private key, or None if version not found.
        """
        private_keys: dict[str, str] = self._state.get("private_keys", {})  # type: ignore[assignment]
        return private_keys.get(version)

    @property
    def user_id(self) -> str | None:
        """Bot's X user ID from state.json."""
        return self._state.get("user_id")  # type: ignore[return-value]

    @property
    def signing_key_version(self) -> str | None:
        """Current signing key version from state.json."""
        return self._state.get("signing_key_version")  # type: ignore[return-value]
